#ifndef GOC_CONFIG_H
#define GOC_CONFIG_H

#define GOC_DEAD_COUNT_THRESHOLD 8
#define GOC_ALTS_STACK_THRESHOLD 8
#define GOC_MAX_LIVE_FIBERS_PER_THREAD 64
#define GOC_MIN_MAX_LIVE_FIBERS 256

#endif /* GOC_CONFIG_H */
